set -g mouse on
set -g pane-border-status top
set -g pane-border-format " [Window ###I, Pane ###P] "

set -g pane-border-style fg=grey
set -g pane-active-border-style fg=yellow,bold
set -g base-index 1
setw -g pane-base-index 1

setw -g aggressive-resize on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",xterm-256color:RGB"

set -g set-clipboard on
set -g allow-passthrough on
